name: Sunrise bedroom
on: 
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * *"



permissions:
  id-token: write
  contents: read

jobs:
  turn_on_sunrise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'